url: https://adaptechio.github.io/

# Site settings
title: AdapTech LLC
email: chameleon@adaptech.io
description: "This is an awesome description for AdapTech LLC."
version: "v0.1.0"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/adaptechio

# Build settings
markdown: kramdown
permalink: pretty
