url: https://adaptechio.github.io/

# Site settings
title: AdapTech LLC
copyright_date: "01/01/2022"
email: chameleon@adaptech.io
description: "This is an awesome description for AdapTech LLC."
version: "v0.1.0"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/adaptechio


collections:
  press-releases:
    output: true
    permalink: about/:collection/:path

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - js/node_modules
  - README.md
  - .gitignore
  - docker-compose.yml
  - Dockerfile
  - .dockerignore
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE