---
version: '3'

services:
  adaptechio-site:
    build:
      context: ./
    restart: unless-stopped
    environment:
      SITE_VERSION: dev
    labels:
      - "ORG=AdapTech.io"
    volumes:
      - "./:/usr/src/app"
      - "./_site/:/_site/"
      - "./_sass/:/_sass/"
    ports:
    - "4000:4000"
